### ISSUE TITLE
Certain gems not showing up in search

### ISSUE THREAD

**Issue by aiolos01** [testpushpleaseignore/acquisition#29]
Stormbind and Predator don't appear in search regardless of the type of tab they're in. All the other gems that I've checked and all items appear normally. It's just those two that don't show up.

**Comment by testpushpleaseignore** [comment]
Oh I see what's going on, at least for the Predator Support, since it has technically two skills within the gem, it's pulling the Signal Prey skill as the gem name. I should hopefully have this fixed here on my end, and can work on getting a release out here later with that fix. Thanks for the find!

![image](https://user-images.githubusercontent.com/26693973/210151279-5e764c73-60e0-4c0c-8a59-09d593ca8ced.png)

![image](https://user-images.githubusercontent.com/26693973/210151310-b112b0e9-6f0d-4545-8343-cbd6d8dcfbb7.png)

**Comment by testpushpleaseignore** [comment]
Should have v0.9.7 released now to fix this issue.

**Comment by aiolos01** [comment]
Yup, problem solved. Thanks for the (truly) immediate response and Happy New Year.

**Comment by aiolos01** [comment]
Hello again. Just noticed that the fix eliminated all the vaal gems.
